### PR TITLE
Add ServiceList#provideLayer

### PR DESCRIPTION
**Pull request by cipriansofronia**
This adds the possibility to provide dependencies via `ZManaged#provideLayer`.

### CODE REVIEW

**Comment by thesamet** [comment]
Thanks for this contribution, @cipriansofronia !

**Comment by cipriansofronia** [comment]
Oh wow, that was super fast :rocket: :1st_place_medal: Would you mind releasing a new RC with this change, please? :sweat_smile:

**Comment by thesamet** [comment]
Planning to cut a final 0.4.0 today/tomorrow. We do have a SNAPSHOT release on each commit which you can use in the mean time.

**Comment by cipriansofronia** [comment]
Oh, cool! I can work with that! Many thanks! :beers:

**Comment by thesamet** [comment]
FWIW, the only block to final 0.4.0 is a single test that occasionally fails in CI, but never locally - not sure if the test code has a race condition or it's in zio-grpc core... https://github.com/scalapb/zio-grpc/runs/976797002?check_suite_focus=true

**Comment by cipriansofronia** [comment]
I see, indeed, all tests passed on my local machine as well.

**Pull request merged**
