### PR TITLE
wip: update to zio-2.0.0-RC6

### PR DESCRIPTION
**Pull request by desavitsky**

### CODE REVIEW

**Comment by thesamet** [comment]
Hey, this looks great! Since the master branch is already on ZIO2, I'd like to remove the zio2 branch to prevent confusion and duplication of commits. Can you rebase on top of master and squash all the changes to a single commit? 

Once that's merged, I'll make a milestone release that will allow to bring the examples up to date.

**Comment by desavitsky** [comment]
Okay, will do!

**Comment by desavitsky** [comment]
squashed commits into one and directed the PR to master
(didn't get why no checks but summary started and there is not message that requires an approval to run the rest of checks)

**Comment by desavitsky** [comment]
what I did except bumping zio version: I had to downgrade zioGrpcVersion from 0.6.0-test to 0.5.1 because on newer version code didn't see proto-compiled classes

**Comment by e-Evolution** [comment]
Hi guys, thanks for your great effort and supporting ZIO 2, I tried to compile the project on Apple M1 Max and got some errors

[error] lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
[error] https://repo1.maven.org/maven2/com/google/protobuf/protoc/3.13.0/protoc-3.13.0-osx-aarch_64.exe: not found: https://repo1.maven. org/maven2/com/google/protobuf/protoc/3.13.0/protoc-3.13.0-osx-aarch_64.exe

to solve update build.sbt in the line to PB.protocVersion := "3.20.1", I hope the suggestion is useful

**Pull request merged**
