### PR TITLE
Update backpressure docs

### PR DESCRIPTION
**Pull request by ghostdogpr**
In response to https://github.com/scalapb/zio-grpc/pull/578#issuecomment-1821838765

The changelog currently is about "Unreleased - 0.6.0", but this version was released so I am not sure what to do with it.

### CODE REVIEW

**Comment by thesamet** [comment]
> The changelog currently is about "Unreleased - 0.6.0", but this version was released so I am not sure what to do with it.

No worries about the CHANGELOG. Thanks for updating the docs!

**Comment by ghostdogpr** [comment]
@thesamet any chance to make a 0.6.1 with this change? 🙏

**Comment by thesamet** [comment]
Released 0.6.1

-Nadav

**Comment by ghostdogpr** [comment]
Thanks!

**Pull request merged**
