### PR TITLE
bumped grpc version

### PR DESCRIPTION
**Pull request by Adriani277**
The grpc version being used does not seem to be compatible with higher versions, namely `1.54.2`

### CODE REVIEW

**Comment by Adriani277** [comment]
@thesamet could you kindly have a look at this

**Comment by Adriani277** [comment]
@thesamet is there any timeline as to when this will be released?

**Comment by thesamet** [comment]
Hi @Adriani277 , there's no timeline for the next release. In the meantime, you should be able to set the desired version of grpc within your project.

**Comment by thesamet** [comment]
Having said that, there is a snapshot release for each commit, and the latest is 0.6.0+25-e26113ae-SNAPSHOT - so you can use that to try and see if it helps with the compatibility issue you mentioned in the original message.

**Comment by Adriani277** [comment]
Thanks, I will have to go with the snapshot in this case. We have a compatibility issue due to also having akka grpc which relies on the higher version of netty-shaded

**Pull request merged**
